# Generated by Django 2.1.4 on 2018-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='attach',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
