# Generated by Django 2.1.4 on 2018-12-21 20:46

import datetime
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20181221_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attach',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 15, 46, 33, 34443)),
        ),
        migrations.AlterField(
            model_name='attach',
            name='image',
            field=models.FileField(upload_to=documents.models.PathAndRename('images/uploads/2018/12/21'), validators=[documents.models.upload_pdf_validator]),
        ),
    ]
